// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// !
/// Returns the bitrate of the file in kb/s.
@ffi.Native<ffi.Int Function(ffi.Pointer<TagLib_AudioProperties>)>()
external int taglib_audioproperties_bitrate(
  ffi.Pointer<TagLib_AudioProperties> audioProperties,
);

/// !
/// Returns the number of channels in the audio stream.
@ffi.Native<ffi.Int Function(ffi.Pointer<TagLib_AudioProperties>)>()
external int taglib_audioproperties_channels(
  ffi.Pointer<TagLib_AudioProperties> audioProperties,
);

/// !
/// Returns the length of the file in seconds.
@ffi.Native<ffi.Int Function(ffi.Pointer<TagLib_AudioProperties>)>()
external int taglib_audioproperties_length(
  ffi.Pointer<TagLib_AudioProperties> audioProperties,
);

/// !
/// Returns the sample rate of the file in Hz.
@ffi.Native<ffi.Int Function(ffi.Pointer<TagLib_AudioProperties>)>()
external int taglib_audioproperties_samplerate(
  ffi.Pointer<TagLib_AudioProperties> audioProperties,
);

/// !
/// Frees the NULL terminated array \a props of property attribute arrays
/// (as returned by taglib_complex_property_get()) and the data such as
/// C-strings and byte vectors contained in these attributes.
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>>,
  )
>()
external void taglib_complex_property_free(
  ffi.Pointer<ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>>
  props,
);

/// !
/// Frees the NULL terminated array \a keys (as returned by
/// taglib_complex_property_keys()) and the C-strings it contains.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external void taglib_complex_property_free_keys(
  ffi.Pointer<ffi.Pointer<ffi.Char>> keys,
);

/// !
/// Get value(s) of complex property \a key.
///
/// \return NULL terminated array of property values, which are themselves an
/// array of property attributes, only NULL if empty.
/// It must be freed by the client using taglib_complex_property_free().
@ffi.Native<
  ffi.Pointer<ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>>
  Function(ffi.Pointer<TagLib_File>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<
  ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>
>
taglib_complex_property_get(
  ffi.Pointer<TagLib_File> file,
  ffi.Pointer<ffi.Char> key,
);

/// !
/// Get the keys of the complex properties.
///
/// \return NULL terminated array of C-strings (char *), only NULL if empty.
/// It must be freed by the client using taglib_complex_property_free_keys().
@ffi.Native<
  ffi.Pointer<ffi.Pointer<ffi.Char>> Function(ffi.Pointer<TagLib_File>)
>()
external ffi.Pointer<ffi.Pointer<ffi.Char>> taglib_complex_property_keys(
  ffi.Pointer<TagLib_File> file,
);

/// !
/// Sets the complex property \a key with \a value.  Use \a value = NULL to
/// remove the property, otherwise it will be replaced with the NULL
/// terminated array of attributes in \a value.
///
/// A picture can be set with the TAGLIB_COMPLEX_PROPERTY_PICTURE macro:
///
/// \code {.c}
/// TagLib_File *file = taglib_file_new("myfile.mp3");
/// FILE *fh = fopen("mypicture.jpg", "rb");
/// if(fh) {
/// fseek(fh, 0L, SEEK_END);
/// long size = ftell(fh);
/// fseek(fh, 0L, SEEK_SET);
/// char *data = (char *)malloc(size);
/// fread(data, size, 1, fh);
/// TAGLIB_COMPLEX_PROPERTY_PICTURE(props, data, size, "Written by TagLib",
/// "image/jpeg", "Front Cover");
/// taglib_complex_property_set(file, "PICTURE", props);
/// taglib_file_save(file);
/// free(data);
/// fclose(fh);
/// }
/// \endcode
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<TagLib_File>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>,
  )
>()
external int taglib_complex_property_set(
  ffi.Pointer<TagLib_File> file,
  ffi.Pointer<ffi.Char> key,
  ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>> value,
);

/// !
/// Appends \a value to the complex property \a key (sets it if non-existing).
/// Use \a value = NULL to remove all values associated with the \a key.
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<TagLib_File>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>,
  )
>()
external int taglib_complex_property_set_append(
  ffi.Pointer<TagLib_File> file,
  ffi.Pointer<ffi.Char> key,
  ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>> value,
);

/// !
/// Returns a pointer to the audio properties associated with this file.  This
/// will be freed automatically when the file is freed.
@ffi.Native<
  ffi.Pointer<TagLib_AudioProperties> Function(ffi.Pointer<TagLib_File>)
>()
external ffi.Pointer<TagLib_AudioProperties> taglib_file_audioproperties(
  ffi.Pointer<TagLib_File> file,
);

/// !
/// Frees and closes the file.
@ffi.Native<ffi.Void Function(ffi.Pointer<TagLib_File>)>()
external void taglib_file_free(ffi.Pointer<TagLib_File> file);

/// !
/// Returns \c true if the file is open and readable and valid information for
/// the Tag and / or AudioProperties was found.
@ffi.Native<ffi.Int Function(ffi.Pointer<TagLib_File>)>()
external int taglib_file_is_valid(ffi.Pointer<TagLib_File> file);

/// !
/// Creates a TagLib file based on \a filename.  TagLib will try to guess the file
/// type.
///
/// \returns NULL if the file type cannot be determined or the file cannot
/// be opened.
@ffi.Native<ffi.Pointer<TagLib_File> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<TagLib_File> taglib_file_new(
  ffi.Pointer<ffi.Char> filename,
);

/// !
/// Creates a TagLib file from a \a stream.
/// A byte vector stream can be used to read a file from memory and write to
/// memory, e.g. when fetching network data.
/// The stream has to be created using taglib_memory_iostream_new() and shall be
/// freed using taglib_iostream_free() \e after this file is freed with
/// taglib_file_free().
@ffi.Native<ffi.Pointer<TagLib_File> Function(ffi.Pointer<TagLib_IOStream>)>()
external ffi.Pointer<TagLib_File> taglib_file_new_iostream(
  ffi.Pointer<TagLib_IOStream> stream,
);

/// !
/// Creates a TagLib file based on \a filename.  Rather than attempting to guess
/// the type, it will use the one specified by \a type.
@ffi.Native<
  ffi.Pointer<TagLib_File> Function(ffi.Pointer<ffi.Char>, ffi.UnsignedInt)
>(symbol: 'taglib_file_new_type')
external ffi.Pointer<TagLib_File> _taglib_file_new_type(
  ffi.Pointer<ffi.Char> filename,
  int type,
);

ffi.Pointer<TagLib_File> taglib_file_new_type(
  ffi.Pointer<ffi.Char> filename,
  TagLib_File_Type type,
) {
  return _taglib_file_new_type(filename, type.value);
}

/// !
/// Saves the \a file to disk.
@ffi.Native<ffi.Int Function(ffi.Pointer<TagLib_File>)>()
external int taglib_file_save(ffi.Pointer<TagLib_File> file);

/// !
/// Returns a pointer to the tag associated with this file.  This will be freed
/// automatically when the file is freed.
@ffi.Native<ffi.Pointer<TagLib_Tag> Function(ffi.Pointer<TagLib_File>)>()
external ffi.Pointer<TagLib_Tag> taglib_file_tag(ffi.Pointer<TagLib_File> file);

/// !
/// Explicitly free a string returned from TagLib
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void taglib_free(ffi.Pointer<ffi.Void> pointer);

/// !
/// This sets the default encoding for ID3v2 frames that are written to tags.
@ffi.Native<ffi.Void Function(ffi.UnsignedInt)>(
  symbol: 'taglib_id3v2_set_default_text_encoding',
)
external void _taglib_id3v2_set_default_text_encoding(int encoding);

void taglib_id3v2_set_default_text_encoding(TagLib_ID3v2_Encoding encoding) {
  return _taglib_id3v2_set_default_text_encoding(encoding.value);
}

/// !
/// Frees and closes the stream.
@ffi.Native<ffi.Void Function(ffi.Pointer<TagLib_IOStream>)>()
external void taglib_iostream_free(ffi.Pointer<TagLib_IOStream> stream);

/// !
/// Creates a byte vector stream from \a size bytes of \a data.
/// Such a stream can be used with taglib_file_new_iostream() to create a file
/// from memory.
@ffi.Native<
  ffi.Pointer<TagLib_IOStream> Function(ffi.Pointer<ffi.Char>, ffi.UnsignedInt)
>()
external ffi.Pointer<TagLib_IOStream> taglib_memory_iostream_new(
  ffi.Pointer<ffi.Char> data,
  int size,
);

/// !
/// Extract the complex property values of a picture.
///
/// This function can be used to get the data from a "PICTURE" complex property
/// without having to traverse the whole variant map. A picture can be
/// retrieved like this:
///
/// \code {.c}
/// TagLib_File *file = taglib_file_new("myfile.mp3");
/// TagLib_Complex_Property_Attribute*** properties =
/// taglib_complex_property_get(file, "PICTURE");
/// TagLib_Complex_Property_Picture_Data picture;
/// taglib_picture_from_complex_property(properties, &picture);
/// // Do something with picture.mimeType, picture.description,
/// // picture.pictureType, picture.data, picture.size, e.g. extract it.
/// FILE *fh = fopen("mypicture.jpg", "wb");
/// if(fh) {
/// fwrite(picture.data, picture.size, 1, fh);
/// fclose(fh);
/// }
/// taglib_complex_property_free(properties);
/// \endcode
///
/// Note that the data in \a picture contains pointers to data in \a properties,
/// i.e. it only lives as long as the properties, until they are freed with
/// taglib_complex_property_free().
/// If you want to access multiple pictures or additional properties of FLAC
/// pictures ("width", "height", "numColors", "colorDepth" int values), you
/// have to traverse the \a properties yourself.
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>>,
    ffi.Pointer<TagLib_Complex_Property_Picture_Data>,
  )
>()
external void taglib_picture_from_complex_property(
  ffi.Pointer<ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>>
  properties,
  ffi.Pointer<TagLib_Complex_Property_Picture_Data> picture,
);

/// !
/// Frees the NULL terminated array \a props and the C-strings it contains.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external void taglib_property_free(ffi.Pointer<ffi.Pointer<ffi.Char>> props);

/// !
/// Get value(s) of property \a prop.
///
/// \return NULL terminated array of C-strings (char *), only NULL if empty.
/// It must be freed by the client using taglib_property_free().
@ffi.Native<
  ffi.Pointer<ffi.Pointer<ffi.Char>> Function(
    ffi.Pointer<TagLib_File>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<ffi.Pointer<ffi.Char>> taglib_property_get(
  ffi.Pointer<TagLib_File> file,
  ffi.Pointer<ffi.Char> prop,
);

/// !
/// Get the keys of the property map.
///
/// \return NULL terminated array of C-strings (char *), only NULL if empty.
/// It must be freed by the client using taglib_property_free().
@ffi.Native<
  ffi.Pointer<ffi.Pointer<ffi.Char>> Function(ffi.Pointer<TagLib_File>)
>()
external ffi.Pointer<ffi.Pointer<ffi.Char>> taglib_property_keys(
  ffi.Pointer<TagLib_File> file,
);

/// !
/// Sets the property \a prop with \a value.  Use \a value = NULL to remove
/// the property, otherwise it will be replaced.
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TagLib_File>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external void taglib_property_set(
  ffi.Pointer<TagLib_File> file,
  ffi.Pointer<ffi.Char> prop,
  ffi.Pointer<ffi.Char> value,
);

/// !
/// Appends \a value to the property \a prop (sets it if non-existing).
/// Use \a value = NULL to remove all values associated with the property.
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<TagLib_File>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external void taglib_property_set_append(
  ffi.Pointer<TagLib_File> file,
  ffi.Pointer<ffi.Char> prop,
  ffi.Pointer<ffi.Char> value,
);

/// !
/// TagLib can keep track of strings that are created when outputting tag values
/// and clear them using taglib_tag_clear_strings().  This is enabled by default.
/// However if you wish to do more fine grained management of strings, you can do
/// so by setting \a management to FALSE.
@ffi.Native<ffi.Void Function(ffi.Int)>()
external void taglib_set_string_management_enabled(int management);

/// !
/// By default all strings coming into or out of TagLib's C API are in UTF8.
/// However, it may be desirable for TagLib to operate on Latin1 (ISO-8859-1)
/// strings in which case this should be set to FALSE.
@ffi.Native<ffi.Void Function(ffi.Int)>()
external void taglib_set_strings_unicode(int unicode);

/// !
/// Returns a string with this tag's album name.
///
/// \note By default this string should be UTF8 encoded and its memory should be
/// freed using taglib_tag_free_strings().
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<TagLib_Tag>)>()
external ffi.Pointer<ffi.Char> taglib_tag_album(ffi.Pointer<TagLib_Tag> tag);

/// !
/// Returns a string with this tag's artist.
///
/// \note By default this string should be UTF8 encoded and its memory should be
/// freed using taglib_tag_free_strings().
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<TagLib_Tag>)>()
external ffi.Pointer<ffi.Char> taglib_tag_artist(ffi.Pointer<TagLib_Tag> tag);

/// !
/// Returns a string with this tag's comment.
///
/// \note By default this string should be UTF8 encoded and its memory should be
/// freed using taglib_tag_free_strings().
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<TagLib_Tag>)>()
external ffi.Pointer<ffi.Char> taglib_tag_comment(ffi.Pointer<TagLib_Tag> tag);

/// !
/// Frees all of the strings that have been created by the tag.
@ffi.Native<ffi.Void Function()>()
external void taglib_tag_free_strings();

/// !
/// Returns a string with this tag's genre.
///
/// \note By default this string should be UTF8 encoded and its memory should be
/// freed using taglib_tag_free_strings().
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<TagLib_Tag>)>()
external ffi.Pointer<ffi.Char> taglib_tag_genre(ffi.Pointer<TagLib_Tag> tag);

/// !
/// Sets the tag's album.
///
/// \note By default this string should be UTF8 encoded.
@ffi.Native<ffi.Void Function(ffi.Pointer<TagLib_Tag>, ffi.Pointer<ffi.Char>)>()
external void taglib_tag_set_album(
  ffi.Pointer<TagLib_Tag> tag,
  ffi.Pointer<ffi.Char> album,
);

/// !
/// Sets the tag's artist.
///
/// \note By default this string should be UTF8 encoded.
@ffi.Native<ffi.Void Function(ffi.Pointer<TagLib_Tag>, ffi.Pointer<ffi.Char>)>()
external void taglib_tag_set_artist(
  ffi.Pointer<TagLib_Tag> tag,
  ffi.Pointer<ffi.Char> artist,
);

/// !
/// Sets the tag's comment.
///
/// \note By default this string should be UTF8 encoded.
@ffi.Native<ffi.Void Function(ffi.Pointer<TagLib_Tag>, ffi.Pointer<ffi.Char>)>()
external void taglib_tag_set_comment(
  ffi.Pointer<TagLib_Tag> tag,
  ffi.Pointer<ffi.Char> comment,
);

/// !
/// Sets the tag's genre.
///
/// \note By default this string should be UTF8 encoded.
@ffi.Native<ffi.Void Function(ffi.Pointer<TagLib_Tag>, ffi.Pointer<ffi.Char>)>()
external void taglib_tag_set_genre(
  ffi.Pointer<TagLib_Tag> tag,
  ffi.Pointer<ffi.Char> genre,
);

/// !
/// Sets the tag's title.
///
/// \note By default this string should be UTF8 encoded.
@ffi.Native<ffi.Void Function(ffi.Pointer<TagLib_Tag>, ffi.Pointer<ffi.Char>)>()
external void taglib_tag_set_title(
  ffi.Pointer<TagLib_Tag> tag,
  ffi.Pointer<ffi.Char> title,
);

/// !
/// Sets the tag's track number.  0 indicates that this field should be cleared.
@ffi.Native<ffi.Void Function(ffi.Pointer<TagLib_Tag>, ffi.UnsignedInt)>()
external void taglib_tag_set_track(ffi.Pointer<TagLib_Tag> tag, int track);

/// !
/// Sets the tag's year.  0 indicates that this field should be cleared.
@ffi.Native<ffi.Void Function(ffi.Pointer<TagLib_Tag>, ffi.UnsignedInt)>()
external void taglib_tag_set_year(ffi.Pointer<TagLib_Tag> tag, int year);

/// !
/// Returns a string with this tag's title.
///
/// \note By default this string should be UTF8 encoded and its memory should be
/// freed using taglib_tag_free_strings().
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<TagLib_Tag>)>()
external ffi.Pointer<ffi.Char> taglib_tag_title(ffi.Pointer<TagLib_Tag> tag);

/// !
/// Returns the tag's track number or 0 if the track number is not set.
@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<TagLib_Tag>)>()
external int taglib_tag_track(ffi.Pointer<TagLib_Tag> tag);

/// !
/// Returns the tag's year or 0 if the year is not set.
@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<TagLib_Tag>)>()
external int taglib_tag_year(ffi.Pointer<TagLib_Tag> tag);

final class TagLib_AudioProperties extends ffi.Struct {
  @ffi.Int()
  external int dummy;

  static ffi.Pointer<TagLib_AudioProperties> $allocate(
    ffi.Allocator $allocator, {
    required int dummy,
  }) => $allocator<TagLib_AudioProperties>()..ref.dummy = dummy;
}

/// !
/// Attribute of a complex property.
/// Complex properties consist of a NULL-terminated array of pointers to
/// this structure with \e key and \e value.
final class TagLib_Complex_Property_Attribute extends ffi.Struct {
  external ffi.Pointer<ffi.Char> key;

  external TagLib_Variant value;
}

/// !
/// Picture data extracted from a complex property by the convenience function
/// taglib_picture_from_complex_property().
final class TagLib_Complex_Property_Picture_Data extends ffi.Struct {
  external ffi.Pointer<ffi.Char> mimeType;

  external ffi.Pointer<ffi.Char> description;

  external ffi.Pointer<ffi.Char> pictureType;

  external ffi.Pointer<ffi.Char> data;

  @ffi.UnsignedInt()
  external int size;

  static ffi.Pointer<TagLib_Complex_Property_Picture_Data> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> mimeType,
    required ffi.Pointer<ffi.Char> description,
    required ffi.Pointer<ffi.Char> pictureType,
    required ffi.Pointer<ffi.Char> data,
    required int size,
  }) => $allocator<TagLib_Complex_Property_Picture_Data>()
    ..ref.mimeType = mimeType
    ..ref.description = description
    ..ref.pictureType = pictureType
    ..ref.data = data
    ..ref.size = size;
}

/// These are used to give the C API some type safety (as opposed to
/// using void * ), but pointers to them are simply cast to the corresponding C++
/// types in the implementation.
final class TagLib_File extends ffi.Struct {
  @ffi.Int()
  external int dummy;

  static ffi.Pointer<TagLib_File> $allocate(
    ffi.Allocator $allocator, {
    required int dummy,
  }) => $allocator<TagLib_File>()..ref.dummy = dummy;
}

/// File API
enum TagLib_File_Type {
  TagLib_File_MPEG(0),
  TagLib_File_OggVorbis(1),
  TagLib_File_FLAC(2),
  TagLib_File_MPC(3),
  TagLib_File_OggFlac(4),
  TagLib_File_WavPack(5),
  TagLib_File_Speex(6),
  TagLib_File_TrueAudio(7),
  TagLib_File_MP4(8),
  TagLib_File_ASF(9),
  TagLib_File_AIFF(10),
  TagLib_File_WAV(11),
  TagLib_File_APE(12),
  TagLib_File_IT(13),
  TagLib_File_Mod(14),
  TagLib_File_S3M(15),
  TagLib_File_XM(16),
  TagLib_File_Opus(17),
  TagLib_File_DSF(18),
  TagLib_File_DSDIFF(19),
  TagLib_File_SHORTEN(20),
  TagLib_File_MATROSKA(21);

  final int value;
  const TagLib_File_Type(this.value);

  static TagLib_File_Type fromValue(int value) => switch (value) {
    0 => TagLib_File_MPEG,
    1 => TagLib_File_OggVorbis,
    2 => TagLib_File_FLAC,
    3 => TagLib_File_MPC,
    4 => TagLib_File_OggFlac,
    5 => TagLib_File_WavPack,
    6 => TagLib_File_Speex,
    7 => TagLib_File_TrueAudio,
    8 => TagLib_File_MP4,
    9 => TagLib_File_ASF,
    10 => TagLib_File_AIFF,
    11 => TagLib_File_WAV,
    12 => TagLib_File_APE,
    13 => TagLib_File_IT,
    14 => TagLib_File_Mod,
    15 => TagLib_File_S3M,
    16 => TagLib_File_XM,
    17 => TagLib_File_Opus,
    18 => TagLib_File_DSF,
    19 => TagLib_File_DSDIFF,
    20 => TagLib_File_SHORTEN,
    21 => TagLib_File_MATROSKA,
    _ => throw ArgumentError('Unknown value for TagLib_File_Type: $value'),
  };
}

/// Special convenience ID3v2 functions
enum TagLib_ID3v2_Encoding {
  TagLib_ID3v2_Latin1(0),
  TagLib_ID3v2_UTF16(1),
  TagLib_ID3v2_UTF16BE(2),
  TagLib_ID3v2_UTF8(3);

  final int value;
  const TagLib_ID3v2_Encoding(this.value);

  static TagLib_ID3v2_Encoding fromValue(int value) => switch (value) {
    0 => TagLib_ID3v2_Latin1,
    1 => TagLib_ID3v2_UTF16,
    2 => TagLib_ID3v2_UTF16BE,
    3 => TagLib_ID3v2_UTF8,
    _ => throw ArgumentError('Unknown value for TagLib_ID3v2_Encoding: $value'),
  };
}

final class TagLib_IOStream extends ffi.Struct {
  @ffi.Int()
  external int dummy;

  static ffi.Pointer<TagLib_IOStream> $allocate(
    ffi.Allocator $allocator, {
    required int dummy,
  }) => $allocator<TagLib_IOStream>()..ref.dummy = dummy;
}

final class TagLib_Tag extends ffi.Struct {
  @ffi.Int()
  external int dummy;

  static ffi.Pointer<TagLib_Tag> $allocate(
    ffi.Allocator $allocator, {
    required int dummy,
  }) => $allocator<TagLib_Tag>()..ref.dummy = dummy;
}

/// !
/// Discriminated union used in complex property attributes.
///
/// \e type must be set according to the \e value union used.
/// \e size is only required for TagLib_Variant_ByteVector and must contain
/// the number of bytes.
///
/// \related TagLib::Variant.
final class TagLib_Variant extends ffi.Struct {
  @ffi.UnsignedInt()
  external int typeAsInt;

  TagLib_Variant_Type get type => TagLib_Variant_Type.fromValue(typeAsInt);
  set type(TagLib_Variant_Type value) => typeAsInt = value.value;

  @ffi.UnsignedInt()
  external int size;

  external UnnamedUnion value;
}

/// !
/// Types which can be stored in a TagLib_Variant.
///
/// \related TagLib::Variant::Type
/// These correspond to TagLib::Variant::Type, but ByteVectorList, VariantList,
/// VariantMap are not supported and will be returned as their string
/// representation.
enum TagLib_Variant_Type {
  TagLib_Variant_Void(0),
  TagLib_Variant_Bool(1),
  TagLib_Variant_Int(2),
  TagLib_Variant_UInt(3),
  TagLib_Variant_LongLong(4),
  TagLib_Variant_ULongLong(5),
  TagLib_Variant_Double(6),
  TagLib_Variant_String(7),
  TagLib_Variant_StringList(8),
  TagLib_Variant_ByteVector(9);

  final int value;
  const TagLib_Variant_Type(this.value);

  static TagLib_Variant_Type fromValue(int value) => switch (value) {
    0 => TagLib_Variant_Void,
    1 => TagLib_Variant_Bool,
    2 => TagLib_Variant_Int,
    3 => TagLib_Variant_UInt,
    4 => TagLib_Variant_LongLong,
    5 => TagLib_Variant_ULongLong,
    6 => TagLib_Variant_Double,
    7 => TagLib_Variant_String,
    8 => TagLib_Variant_StringList,
    9 => TagLib_Variant_ByteVector,
    _ => throw ArgumentError('Unknown value for TagLib_Variant_Type: $value'),
  };
}

final class UnnamedUnion extends ffi.Union {
  external ffi.Pointer<ffi.Char> stringValue;

  external ffi.Pointer<ffi.Char> byteVectorValue;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> stringListValue;

  @ffi.Int()
  external int boolValue;

  @ffi.Int()
  external int intValue;

  @ffi.UnsignedInt()
  external int uIntValue;

  @ffi.LongLong()
  external int longLongValue;

  @ffi.UnsignedLongLong()
  external int uLongLongValue;

  @ffi.Double()
  external double doubleValue;
}
