// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Bindings for `src/than_audiotag.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class ThanAudiotagBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  ThanAudiotagBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  ThanAudiotagBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// !
  /// Returns the bitrate of the file in kb/s.
  int taglib_audioproperties_bitrate(
    ffi.Pointer<TagLib_AudioProperties> audioProperties,
  ) {
    return _taglib_audioproperties_bitrate(audioProperties);
  }

  late final _taglib_audioproperties_bitratePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<TagLib_AudioProperties>)
        >
      >('taglib_audioproperties_bitrate');
  late final _taglib_audioproperties_bitrate =
      _taglib_audioproperties_bitratePtr
          .asFunction<int Function(ffi.Pointer<TagLib_AudioProperties>)>();

  /// !
  /// Returns the number of channels in the audio stream.
  int taglib_audioproperties_channels(
    ffi.Pointer<TagLib_AudioProperties> audioProperties,
  ) {
    return _taglib_audioproperties_channels(audioProperties);
  }

  late final _taglib_audioproperties_channelsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<TagLib_AudioProperties>)
        >
      >('taglib_audioproperties_channels');
  late final _taglib_audioproperties_channels =
      _taglib_audioproperties_channelsPtr
          .asFunction<int Function(ffi.Pointer<TagLib_AudioProperties>)>();

  /// !
  /// Returns the length of the file in seconds.
  int taglib_audioproperties_length(
    ffi.Pointer<TagLib_AudioProperties> audioProperties,
  ) {
    return _taglib_audioproperties_length(audioProperties);
  }

  late final _taglib_audioproperties_lengthPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<TagLib_AudioProperties>)
        >
      >('taglib_audioproperties_length');
  late final _taglib_audioproperties_length = _taglib_audioproperties_lengthPtr
      .asFunction<int Function(ffi.Pointer<TagLib_AudioProperties>)>();

  /// !
  /// Returns the sample rate of the file in Hz.
  int taglib_audioproperties_samplerate(
    ffi.Pointer<TagLib_AudioProperties> audioProperties,
  ) {
    return _taglib_audioproperties_samplerate(audioProperties);
  }

  late final _taglib_audioproperties_sampleratePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<TagLib_AudioProperties>)
        >
      >('taglib_audioproperties_samplerate');
  late final _taglib_audioproperties_samplerate =
      _taglib_audioproperties_sampleratePtr
          .asFunction<int Function(ffi.Pointer<TagLib_AudioProperties>)>();

  /// !
  /// Frees the NULL terminated array \a props of property attribute arrays
  /// (as returned by taglib_complex_property_get()) and the data such as
  /// C-strings and byte vectors contained in these attributes.
  void taglib_complex_property_free(
    ffi.Pointer<ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>>
    props,
  ) {
    return _taglib_complex_property_free(props);
  }

  late final _taglib_complex_property_freePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<
              ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>
            >,
          )
        >
      >('taglib_complex_property_free');
  late final _taglib_complex_property_free = _taglib_complex_property_freePtr
      .asFunction<
        void Function(
          ffi.Pointer<
            ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>
          >,
        )
      >();

  /// !
  /// Frees the NULL terminated array \a keys (as returned by
  /// taglib_complex_property_keys()) and the C-strings it contains.
  void taglib_complex_property_free_keys(
    ffi.Pointer<ffi.Pointer<ffi.Char>> keys,
  ) {
    return _taglib_complex_property_free_keys(keys);
  }

  late final _taglib_complex_property_free_keysPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)
        >
      >('taglib_complex_property_free_keys');
  late final _taglib_complex_property_free_keys =
      _taglib_complex_property_free_keysPtr
          .asFunction<void Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// !
  /// Get value(s) of complex property \a key.
  ///
  /// \return NULL terminated array of property values, which are themselves an
  /// array of property attributes, only NULL if empty.
  /// It must be freed by the client using taglib_complex_property_free().
  ffi.Pointer<ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>>
  taglib_complex_property_get(
    ffi.Pointer<TagLib_File> file,
    ffi.Pointer<ffi.Char> key,
  ) {
    return _taglib_complex_property_get(file, key);
  }

  late final _taglib_complex_property_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<
            ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>
          >
          Function(ffi.Pointer<TagLib_File>, ffi.Pointer<ffi.Char>)
        >
      >('taglib_complex_property_get');
  late final _taglib_complex_property_get = _taglib_complex_property_getPtr
      .asFunction<
        ffi.Pointer<ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>>
        Function(ffi.Pointer<TagLib_File>, ffi.Pointer<ffi.Char>)
      >();

  /// !
  /// Get the keys of the complex properties.
  ///
  /// \return NULL terminated array of C-strings (char *), only NULL if empty.
  /// It must be freed by the client using taglib_complex_property_free_keys().
  ffi.Pointer<ffi.Pointer<ffi.Char>> taglib_complex_property_keys(
    ffi.Pointer<TagLib_File> file,
  ) {
    return _taglib_complex_property_keys(file);
  }

  late final _taglib_complex_property_keysPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Pointer<ffi.Char>> Function(ffi.Pointer<TagLib_File>)
        >
      >('taglib_complex_property_keys');
  late final _taglib_complex_property_keys = _taglib_complex_property_keysPtr
      .asFunction<
        ffi.Pointer<ffi.Pointer<ffi.Char>> Function(ffi.Pointer<TagLib_File>)
      >();

  /// !
  /// Sets the complex property \a key with \a value.  Use \a value = NULL to
  /// remove the property, otherwise it will be replaced with the NULL
  /// terminated array of attributes in \a value.
  ///
  /// A picture can be set with the TAGLIB_COMPLEX_PROPERTY_PICTURE macro:
  ///
  /// \code {.c}
  /// TagLib_File *file = taglib_file_new("myfile.mp3");
  /// FILE *fh = fopen("mypicture.jpg", "rb");
  /// if(fh) {
  /// fseek(fh, 0L, SEEK_END);
  /// long size = ftell(fh);
  /// fseek(fh, 0L, SEEK_SET);
  /// char *data = (char *)malloc(size);
  /// fread(data, size, 1, fh);
  /// TAGLIB_COMPLEX_PROPERTY_PICTURE(props, data, size, "Written by TagLib",
  /// "image/jpeg", "Front Cover");
  /// taglib_complex_property_set(file, "PICTURE", props);
  /// taglib_file_save(file);
  /// free(data);
  /// fclose(fh);
  /// }
  /// \endcode
  int taglib_complex_property_set(
    ffi.Pointer<TagLib_File> file,
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>> value,
  ) {
    return _taglib_complex_property_set(file, key, value);
  }

  late final _taglib_complex_property_setPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<TagLib_File>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>,
          )
        >
      >('taglib_complex_property_set');
  late final _taglib_complex_property_set = _taglib_complex_property_setPtr
      .asFunction<
        int Function(
          ffi.Pointer<TagLib_File>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>,
        )
      >();

  /// !
  /// Appends \a value to the complex property \a key (sets it if non-existing).
  /// Use \a value = NULL to remove all values associated with the \a key.
  int taglib_complex_property_set_append(
    ffi.Pointer<TagLib_File> file,
    ffi.Pointer<ffi.Char> key,
    ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>> value,
  ) {
    return _taglib_complex_property_set_append(file, key, value);
  }

  late final _taglib_complex_property_set_appendPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<TagLib_File>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>,
          )
        >
      >('taglib_complex_property_set_append');
  late final _taglib_complex_property_set_append =
      _taglib_complex_property_set_appendPtr
          .asFunction<
            int Function(
              ffi.Pointer<TagLib_File>,
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>,
            )
          >();

  /// !
  /// Returns a pointer to the audio properties associated with this file.  This
  /// will be freed automatically when the file is freed.
  ffi.Pointer<TagLib_AudioProperties> taglib_file_audioproperties(
    ffi.Pointer<TagLib_File> file,
  ) {
    return _taglib_file_audioproperties(file);
  }

  late final _taglib_file_audiopropertiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<TagLib_AudioProperties> Function(ffi.Pointer<TagLib_File>)
        >
      >('taglib_file_audioproperties');
  late final _taglib_file_audioproperties = _taglib_file_audiopropertiesPtr
      .asFunction<
        ffi.Pointer<TagLib_AudioProperties> Function(ffi.Pointer<TagLib_File>)
      >();

  /// !
  /// Frees and closes the file.
  void taglib_file_free(ffi.Pointer<TagLib_File> file) {
    return _taglib_file_free(file);
  }

  late final _taglib_file_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TagLib_File>)>>(
        'taglib_file_free',
      );
  late final _taglib_file_free = _taglib_file_freePtr
      .asFunction<void Function(ffi.Pointer<TagLib_File>)>();

  /// !
  /// Returns \c true if the file is open and readable and valid information for
  /// the Tag and / or AudioProperties was found.
  int taglib_file_is_valid(ffi.Pointer<TagLib_File> file) {
    return _taglib_file_is_valid(file);
  }

  late final _taglib_file_is_validPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<TagLib_File>)>>(
        'taglib_file_is_valid',
      );
  late final _taglib_file_is_valid = _taglib_file_is_validPtr
      .asFunction<int Function(ffi.Pointer<TagLib_File>)>();

  /// !
  /// Creates a TagLib file based on \a filename.  TagLib will try to guess the file
  /// type.
  ///
  /// \returns NULL if the file type cannot be determined or the file cannot
  /// be opened.
  ffi.Pointer<TagLib_File> taglib_file_new(ffi.Pointer<ffi.Char> filename) {
    return _taglib_file_new(filename);
  }

  late final _taglib_file_newPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<TagLib_File> Function(ffi.Pointer<ffi.Char>)
        >
      >('taglib_file_new');
  late final _taglib_file_new = _taglib_file_newPtr
      .asFunction<ffi.Pointer<TagLib_File> Function(ffi.Pointer<ffi.Char>)>();

  /// !
  /// Creates a TagLib file from a \a stream.
  /// A byte vector stream can be used to read a file from memory and write to
  /// memory, e.g. when fetching network data.
  /// The stream has to be created using taglib_memory_iostream_new() and shall be
  /// freed using taglib_iostream_free() \e after this file is freed with
  /// taglib_file_free().
  ffi.Pointer<TagLib_File> taglib_file_new_iostream(
    ffi.Pointer<TagLib_IOStream> stream,
  ) {
    return _taglib_file_new_iostream(stream);
  }

  late final _taglib_file_new_iostreamPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<TagLib_File> Function(ffi.Pointer<TagLib_IOStream>)
        >
      >('taglib_file_new_iostream');
  late final _taglib_file_new_iostream = _taglib_file_new_iostreamPtr
      .asFunction<
        ffi.Pointer<TagLib_File> Function(ffi.Pointer<TagLib_IOStream>)
      >();

  /// !
  /// Creates a TagLib file based on \a filename.  Rather than attempting to guess
  /// the type, it will use the one specified by \a type.
  ffi.Pointer<TagLib_File> taglib_file_new_type(
    ffi.Pointer<ffi.Char> filename,
    TagLib_File_Type type,
  ) {
    return _taglib_file_new_type(filename, type.value);
  }

  late final _taglib_file_new_typePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<TagLib_File> Function(
            ffi.Pointer<ffi.Char>,
            ffi.UnsignedInt,
          )
        >
      >('taglib_file_new_type');
  late final _taglib_file_new_type = _taglib_file_new_typePtr
      .asFunction<
        ffi.Pointer<TagLib_File> Function(ffi.Pointer<ffi.Char>, int)
      >();

  /// !
  /// Saves the \a file to disk.
  int taglib_file_save(ffi.Pointer<TagLib_File> file) {
    return _taglib_file_save(file);
  }

  late final _taglib_file_savePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<TagLib_File>)>>(
        'taglib_file_save',
      );
  late final _taglib_file_save = _taglib_file_savePtr
      .asFunction<int Function(ffi.Pointer<TagLib_File>)>();

  /// !
  /// Returns a pointer to the tag associated with this file.  This will be freed
  /// automatically when the file is freed.
  ffi.Pointer<TagLib_Tag> taglib_file_tag(ffi.Pointer<TagLib_File> file) {
    return _taglib_file_tag(file);
  }

  late final _taglib_file_tagPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<TagLib_Tag> Function(ffi.Pointer<TagLib_File>)
        >
      >('taglib_file_tag');
  late final _taglib_file_tag = _taglib_file_tagPtr
      .asFunction<ffi.Pointer<TagLib_Tag> Function(ffi.Pointer<TagLib_File>)>();

  /// !
  /// Explicitly free a string returned from TagLib
  void taglib_free(ffi.Pointer<ffi.Void> pointer) {
    return _taglib_free(pointer);
  }

  late final _taglib_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'taglib_free',
      );
  late final _taglib_free = _taglib_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  /// !
  /// This sets the default encoding for ID3v2 frames that are written to tags.
  void taglib_id3v2_set_default_text_encoding(TagLib_ID3v2_Encoding encoding) {
    return _taglib_id3v2_set_default_text_encoding(encoding.value);
  }

  late final _taglib_id3v2_set_default_text_encodingPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UnsignedInt)>>(
        'taglib_id3v2_set_default_text_encoding',
      );
  late final _taglib_id3v2_set_default_text_encoding =
      _taglib_id3v2_set_default_text_encodingPtr
          .asFunction<void Function(int)>();

  /// !
  /// Frees and closes the stream.
  void taglib_iostream_free(ffi.Pointer<TagLib_IOStream> stream) {
    return _taglib_iostream_free(stream);
  }

  late final _taglib_iostream_freePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<TagLib_IOStream>)>
      >('taglib_iostream_free');
  late final _taglib_iostream_free = _taglib_iostream_freePtr
      .asFunction<void Function(ffi.Pointer<TagLib_IOStream>)>();

  /// !
  /// Creates a byte vector stream from \a size bytes of \a data.
  /// Such a stream can be used with taglib_file_new_iostream() to create a file
  /// from memory.
  ffi.Pointer<TagLib_IOStream> taglib_memory_iostream_new(
    ffi.Pointer<ffi.Char> data,
    int size,
  ) {
    return _taglib_memory_iostream_new(data, size);
  }

  late final _taglib_memory_iostream_newPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<TagLib_IOStream> Function(
            ffi.Pointer<ffi.Char>,
            ffi.UnsignedInt,
          )
        >
      >('taglib_memory_iostream_new');
  late final _taglib_memory_iostream_new = _taglib_memory_iostream_newPtr
      .asFunction<
        ffi.Pointer<TagLib_IOStream> Function(ffi.Pointer<ffi.Char>, int)
      >();

  /// !
  /// Extract the complex property values of a picture.
  ///
  /// This function can be used to get the data from a "PICTURE" complex property
  /// without having to traverse the whole variant map. A picture can be
  /// retrieved like this:
  ///
  /// \code {.c}
  /// TagLib_File *file = taglib_file_new("myfile.mp3");
  /// TagLib_Complex_Property_Attribute*** properties =
  /// taglib_complex_property_get(file, "PICTURE");
  /// TagLib_Complex_Property_Picture_Data picture;
  /// taglib_picture_from_complex_property(properties, &picture);
  /// // Do something with picture.mimeType, picture.description,
  /// // picture.pictureType, picture.data, picture.size, e.g. extract it.
  /// FILE *fh = fopen("mypicture.jpg", "wb");
  /// if(fh) {
  /// fwrite(picture.data, picture.size, 1, fh);
  /// fclose(fh);
  /// }
  /// taglib_complex_property_free(properties);
  /// \endcode
  ///
  /// Note that the data in \a picture contains pointers to data in \a properties,
  /// i.e. it only lives as long as the properties, until they are freed with
  /// taglib_complex_property_free().
  /// If you want to access multiple pictures or additional properties of FLAC
  /// pictures ("width", "height", "numColors", "colorDepth" int values), you
  /// have to traverse the \a properties yourself.
  void taglib_picture_from_complex_property(
    ffi.Pointer<ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>>
    properties,
    ffi.Pointer<TagLib_Complex_Property_Picture_Data> picture,
  ) {
    return _taglib_picture_from_complex_property(properties, picture);
  }

  late final _taglib_picture_from_complex_propertyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<
              ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>
            >,
            ffi.Pointer<TagLib_Complex_Property_Picture_Data>,
          )
        >
      >('taglib_picture_from_complex_property');
  late final _taglib_picture_from_complex_property =
      _taglib_picture_from_complex_propertyPtr
          .asFunction<
            void Function(
              ffi.Pointer<
                ffi.Pointer<ffi.Pointer<TagLib_Complex_Property_Attribute>>
              >,
              ffi.Pointer<TagLib_Complex_Property_Picture_Data>,
            )
          >();

  /// !
  /// Frees the NULL terminated array \a props and the C-strings it contains.
  void taglib_property_free(ffi.Pointer<ffi.Pointer<ffi.Char>> props) {
    return _taglib_property_free(props);
  }

  late final _taglib_property_freePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)
        >
      >('taglib_property_free');
  late final _taglib_property_free = _taglib_property_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Pointer<ffi.Char>>)>();

  /// !
  /// Get value(s) of property \a prop.
  ///
  /// \return NULL terminated array of C-strings (char *), only NULL if empty.
  /// It must be freed by the client using taglib_property_free().
  ffi.Pointer<ffi.Pointer<ffi.Char>> taglib_property_get(
    ffi.Pointer<TagLib_File> file,
    ffi.Pointer<ffi.Char> prop,
  ) {
    return _taglib_property_get(file, prop);
  }

  late final _taglib_property_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Pointer<ffi.Char>> Function(
            ffi.Pointer<TagLib_File>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('taglib_property_get');
  late final _taglib_property_get = _taglib_property_getPtr
      .asFunction<
        ffi.Pointer<ffi.Pointer<ffi.Char>> Function(
          ffi.Pointer<TagLib_File>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// !
  /// Get the keys of the property map.
  ///
  /// \return NULL terminated array of C-strings (char *), only NULL if empty.
  /// It must be freed by the client using taglib_property_free().
  ffi.Pointer<ffi.Pointer<ffi.Char>> taglib_property_keys(
    ffi.Pointer<TagLib_File> file,
  ) {
    return _taglib_property_keys(file);
  }

  late final _taglib_property_keysPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Pointer<ffi.Char>> Function(ffi.Pointer<TagLib_File>)
        >
      >('taglib_property_keys');
  late final _taglib_property_keys = _taglib_property_keysPtr
      .asFunction<
        ffi.Pointer<ffi.Pointer<ffi.Char>> Function(ffi.Pointer<TagLib_File>)
      >();

  /// !
  /// Sets the property \a prop with \a value.  Use \a value = NULL to remove
  /// the property, otherwise it will be replaced.
  void taglib_property_set(
    ffi.Pointer<TagLib_File> file,
    ffi.Pointer<ffi.Char> prop,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _taglib_property_set(file, prop, value);
  }

  late final _taglib_property_setPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<TagLib_File>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('taglib_property_set');
  late final _taglib_property_set = _taglib_property_setPtr
      .asFunction<
        void Function(
          ffi.Pointer<TagLib_File>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// !
  /// Appends \a value to the property \a prop (sets it if non-existing).
  /// Use \a value = NULL to remove all values associated with the property.
  void taglib_property_set_append(
    ffi.Pointer<TagLib_File> file,
    ffi.Pointer<ffi.Char> prop,
    ffi.Pointer<ffi.Char> value,
  ) {
    return _taglib_property_set_append(file, prop, value);
  }

  late final _taglib_property_set_appendPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<TagLib_File>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Char>,
          )
        >
      >('taglib_property_set_append');
  late final _taglib_property_set_append = _taglib_property_set_appendPtr
      .asFunction<
        void Function(
          ffi.Pointer<TagLib_File>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Char>,
        )
      >();

  /// !
  /// TagLib can keep track of strings that are created when outputting tag values
  /// and clear them using taglib_tag_clear_strings().  This is enabled by default.
  /// However if you wish to do more fine grained management of strings, you can do
  /// so by setting \a management to FALSE.
  void taglib_set_string_management_enabled(int management) {
    return _taglib_set_string_management_enabled(management);
  }

  late final _taglib_set_string_management_enabledPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
        'taglib_set_string_management_enabled',
      );
  late final _taglib_set_string_management_enabled =
      _taglib_set_string_management_enabledPtr.asFunction<void Function(int)>();

  /// !
  /// By default all strings coming into or out of TagLib's C API are in UTF8.
  /// However, it may be desirable for TagLib to operate on Latin1 (ISO-8859-1)
  /// strings in which case this should be set to FALSE.
  void taglib_set_strings_unicode(int unicode) {
    return _taglib_set_strings_unicode(unicode);
  }

  late final _taglib_set_strings_unicodePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
        'taglib_set_strings_unicode',
      );
  late final _taglib_set_strings_unicode = _taglib_set_strings_unicodePtr
      .asFunction<void Function(int)>();

  /// !
  /// Returns a string with this tag's album name.
  ///
  /// \note By default this string should be UTF8 encoded and its memory should be
  /// freed using taglib_tag_free_strings().
  ffi.Pointer<ffi.Char> taglib_tag_album(ffi.Pointer<TagLib_Tag> tag) {
    return _taglib_tag_album(tag);
  }

  late final _taglib_tag_albumPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<TagLib_Tag>)
        >
      >('taglib_tag_album');
  late final _taglib_tag_album = _taglib_tag_albumPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<TagLib_Tag>)>();

  /// !
  /// Returns a string with this tag's artist.
  ///
  /// \note By default this string should be UTF8 encoded and its memory should be
  /// freed using taglib_tag_free_strings().
  ffi.Pointer<ffi.Char> taglib_tag_artist(ffi.Pointer<TagLib_Tag> tag) {
    return _taglib_tag_artist(tag);
  }

  late final _taglib_tag_artistPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<TagLib_Tag>)
        >
      >('taglib_tag_artist');
  late final _taglib_tag_artist = _taglib_tag_artistPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<TagLib_Tag>)>();

  /// !
  /// Returns a string with this tag's comment.
  ///
  /// \note By default this string should be UTF8 encoded and its memory should be
  /// freed using taglib_tag_free_strings().
  ffi.Pointer<ffi.Char> taglib_tag_comment(ffi.Pointer<TagLib_Tag> tag) {
    return _taglib_tag_comment(tag);
  }

  late final _taglib_tag_commentPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<TagLib_Tag>)
        >
      >('taglib_tag_comment');
  late final _taglib_tag_comment = _taglib_tag_commentPtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<TagLib_Tag>)>();

  /// !
  /// Frees all of the strings that have been created by the tag.
  void taglib_tag_free_strings() {
    return _taglib_tag_free_strings();
  }

  late final _taglib_tag_free_stringsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
        'taglib_tag_free_strings',
      );
  late final _taglib_tag_free_strings = _taglib_tag_free_stringsPtr
      .asFunction<void Function()>();

  /// !
  /// Returns a string with this tag's genre.
  ///
  /// \note By default this string should be UTF8 encoded and its memory should be
  /// freed using taglib_tag_free_strings().
  ffi.Pointer<ffi.Char> taglib_tag_genre(ffi.Pointer<TagLib_Tag> tag) {
    return _taglib_tag_genre(tag);
  }

  late final _taglib_tag_genrePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<TagLib_Tag>)
        >
      >('taglib_tag_genre');
  late final _taglib_tag_genre = _taglib_tag_genrePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<TagLib_Tag>)>();

  /// !
  /// Sets the tag's album.
  ///
  /// \note By default this string should be UTF8 encoded.
  void taglib_tag_set_album(
    ffi.Pointer<TagLib_Tag> tag,
    ffi.Pointer<ffi.Char> album,
  ) {
    return _taglib_tag_set_album(tag, album);
  }

  late final _taglib_tag_set_albumPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<TagLib_Tag>, ffi.Pointer<ffi.Char>)
        >
      >('taglib_tag_set_album');
  late final _taglib_tag_set_album = _taglib_tag_set_albumPtr
      .asFunction<
        void Function(ffi.Pointer<TagLib_Tag>, ffi.Pointer<ffi.Char>)
      >();

  /// !
  /// Sets the tag's artist.
  ///
  /// \note By default this string should be UTF8 encoded.
  void taglib_tag_set_artist(
    ffi.Pointer<TagLib_Tag> tag,
    ffi.Pointer<ffi.Char> artist,
  ) {
    return _taglib_tag_set_artist(tag, artist);
  }

  late final _taglib_tag_set_artistPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<TagLib_Tag>, ffi.Pointer<ffi.Char>)
        >
      >('taglib_tag_set_artist');
  late final _taglib_tag_set_artist = _taglib_tag_set_artistPtr
      .asFunction<
        void Function(ffi.Pointer<TagLib_Tag>, ffi.Pointer<ffi.Char>)
      >();

  /// !
  /// Sets the tag's comment.
  ///
  /// \note By default this string should be UTF8 encoded.
  void taglib_tag_set_comment(
    ffi.Pointer<TagLib_Tag> tag,
    ffi.Pointer<ffi.Char> comment,
  ) {
    return _taglib_tag_set_comment(tag, comment);
  }

  late final _taglib_tag_set_commentPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<TagLib_Tag>, ffi.Pointer<ffi.Char>)
        >
      >('taglib_tag_set_comment');
  late final _taglib_tag_set_comment = _taglib_tag_set_commentPtr
      .asFunction<
        void Function(ffi.Pointer<TagLib_Tag>, ffi.Pointer<ffi.Char>)
      >();

  /// !
  /// Sets the tag's genre.
  ///
  /// \note By default this string should be UTF8 encoded.
  void taglib_tag_set_genre(
    ffi.Pointer<TagLib_Tag> tag,
    ffi.Pointer<ffi.Char> genre,
  ) {
    return _taglib_tag_set_genre(tag, genre);
  }

  late final _taglib_tag_set_genrePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<TagLib_Tag>, ffi.Pointer<ffi.Char>)
        >
      >('taglib_tag_set_genre');
  late final _taglib_tag_set_genre = _taglib_tag_set_genrePtr
      .asFunction<
        void Function(ffi.Pointer<TagLib_Tag>, ffi.Pointer<ffi.Char>)
      >();

  /// !
  /// Sets the tag's title.
  ///
  /// \note By default this string should be UTF8 encoded.
  void taglib_tag_set_title(
    ffi.Pointer<TagLib_Tag> tag,
    ffi.Pointer<ffi.Char> title,
  ) {
    return _taglib_tag_set_title(tag, title);
  }

  late final _taglib_tag_set_titlePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<TagLib_Tag>, ffi.Pointer<ffi.Char>)
        >
      >('taglib_tag_set_title');
  late final _taglib_tag_set_title = _taglib_tag_set_titlePtr
      .asFunction<
        void Function(ffi.Pointer<TagLib_Tag>, ffi.Pointer<ffi.Char>)
      >();

  /// !
  /// Sets the tag's track number.  0 indicates that this field should be cleared.
  void taglib_tag_set_track(ffi.Pointer<TagLib_Tag> tag, int track) {
    return _taglib_tag_set_track(tag, track);
  }

  late final _taglib_tag_set_trackPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<TagLib_Tag>, ffi.UnsignedInt)
        >
      >('taglib_tag_set_track');
  late final _taglib_tag_set_track = _taglib_tag_set_trackPtr
      .asFunction<void Function(ffi.Pointer<TagLib_Tag>, int)>();

  /// !
  /// Sets the tag's year.  0 indicates that this field should be cleared.
  void taglib_tag_set_year(ffi.Pointer<TagLib_Tag> tag, int year) {
    return _taglib_tag_set_year(tag, year);
  }

  late final _taglib_tag_set_yearPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<TagLib_Tag>, ffi.UnsignedInt)
        >
      >('taglib_tag_set_year');
  late final _taglib_tag_set_year = _taglib_tag_set_yearPtr
      .asFunction<void Function(ffi.Pointer<TagLib_Tag>, int)>();

  /// !
  /// Returns a string with this tag's title.
  ///
  /// \note By default this string should be UTF8 encoded and its memory should be
  /// freed using taglib_tag_free_strings().
  ffi.Pointer<ffi.Char> taglib_tag_title(ffi.Pointer<TagLib_Tag> tag) {
    return _taglib_tag_title(tag);
  }

  late final _taglib_tag_titlePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<ffi.Char> Function(ffi.Pointer<TagLib_Tag>)
        >
      >('taglib_tag_title');
  late final _taglib_tag_title = _taglib_tag_titlePtr
      .asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<TagLib_Tag>)>();

  /// !
  /// Returns the tag's track number or 0 if the track number is not set.
  int taglib_tag_track(ffi.Pointer<TagLib_Tag> tag) {
    return _taglib_tag_track(tag);
  }

  late final _taglib_tag_trackPtr =
      _lookup<
        ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<TagLib_Tag>)>
      >('taglib_tag_track');
  late final _taglib_tag_track = _taglib_tag_trackPtr
      .asFunction<int Function(ffi.Pointer<TagLib_Tag>)>();

  /// !
  /// Returns the tag's year or 0 if the year is not set.
  int taglib_tag_year(ffi.Pointer<TagLib_Tag> tag) {
    return _taglib_tag_year(tag);
  }

  late final _taglib_tag_yearPtr =
      _lookup<
        ffi.NativeFunction<ffi.UnsignedInt Function(ffi.Pointer<TagLib_Tag>)>
      >('taglib_tag_year');
  late final _taglib_tag_year = _taglib_tag_yearPtr
      .asFunction<int Function(ffi.Pointer<TagLib_Tag>)>();
}

final class TagLib_AudioProperties extends ffi.Struct {
  @ffi.Int()
  external int dummy;

  static ffi.Pointer<TagLib_AudioProperties> $allocate(
    ffi.Allocator $allocator, {
    required int dummy,
  }) => $allocator<TagLib_AudioProperties>()..ref.dummy = dummy;
}

/// !
/// Attribute of a complex property.
/// Complex properties consist of a NULL-terminated array of pointers to
/// this structure with \e key and \e value.
final class TagLib_Complex_Property_Attribute extends ffi.Struct {
  external ffi.Pointer<ffi.Char> key;

  external TagLib_Variant value;
}

/// !
/// Picture data extracted from a complex property by the convenience function
/// taglib_picture_from_complex_property().
final class TagLib_Complex_Property_Picture_Data extends ffi.Struct {
  external ffi.Pointer<ffi.Char> mimeType;

  external ffi.Pointer<ffi.Char> description;

  external ffi.Pointer<ffi.Char> pictureType;

  external ffi.Pointer<ffi.Char> data;

  @ffi.UnsignedInt()
  external int size;

  static ffi.Pointer<TagLib_Complex_Property_Picture_Data> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> mimeType,
    required ffi.Pointer<ffi.Char> description,
    required ffi.Pointer<ffi.Char> pictureType,
    required ffi.Pointer<ffi.Char> data,
    required int size,
  }) => $allocator<TagLib_Complex_Property_Picture_Data>()
    ..ref.mimeType = mimeType
    ..ref.description = description
    ..ref.pictureType = pictureType
    ..ref.data = data
    ..ref.size = size;
}

/// These are used to give the C API some type safety (as opposed to
/// using void * ), but pointers to them are simply cast to the corresponding C++
/// types in the implementation.
final class TagLib_File extends ffi.Struct {
  @ffi.Int()
  external int dummy;

  static ffi.Pointer<TagLib_File> $allocate(
    ffi.Allocator $allocator, {
    required int dummy,
  }) => $allocator<TagLib_File>()..ref.dummy = dummy;
}

/// File API
enum TagLib_File_Type {
  TagLib_File_MPEG(0),
  TagLib_File_OggVorbis(1),
  TagLib_File_FLAC(2),
  TagLib_File_MPC(3),
  TagLib_File_OggFlac(4),
  TagLib_File_WavPack(5),
  TagLib_File_Speex(6),
  TagLib_File_TrueAudio(7),
  TagLib_File_MP4(8),
  TagLib_File_ASF(9),
  TagLib_File_AIFF(10),
  TagLib_File_WAV(11),
  TagLib_File_APE(12),
  TagLib_File_IT(13),
  TagLib_File_Mod(14),
  TagLib_File_S3M(15),
  TagLib_File_XM(16),
  TagLib_File_Opus(17),
  TagLib_File_DSF(18),
  TagLib_File_DSDIFF(19),
  TagLib_File_SHORTEN(20),
  TagLib_File_MATROSKA(21);

  final int value;
  const TagLib_File_Type(this.value);

  static TagLib_File_Type fromValue(int value) => switch (value) {
    0 => TagLib_File_MPEG,
    1 => TagLib_File_OggVorbis,
    2 => TagLib_File_FLAC,
    3 => TagLib_File_MPC,
    4 => TagLib_File_OggFlac,
    5 => TagLib_File_WavPack,
    6 => TagLib_File_Speex,
    7 => TagLib_File_TrueAudio,
    8 => TagLib_File_MP4,
    9 => TagLib_File_ASF,
    10 => TagLib_File_AIFF,
    11 => TagLib_File_WAV,
    12 => TagLib_File_APE,
    13 => TagLib_File_IT,
    14 => TagLib_File_Mod,
    15 => TagLib_File_S3M,
    16 => TagLib_File_XM,
    17 => TagLib_File_Opus,
    18 => TagLib_File_DSF,
    19 => TagLib_File_DSDIFF,
    20 => TagLib_File_SHORTEN,
    21 => TagLib_File_MATROSKA,
    _ => throw ArgumentError('Unknown value for TagLib_File_Type: $value'),
  };
}

/// Special convenience ID3v2 functions
enum TagLib_ID3v2_Encoding {
  TagLib_ID3v2_Latin1(0),
  TagLib_ID3v2_UTF16(1),
  TagLib_ID3v2_UTF16BE(2),
  TagLib_ID3v2_UTF8(3);

  final int value;
  const TagLib_ID3v2_Encoding(this.value);

  static TagLib_ID3v2_Encoding fromValue(int value) => switch (value) {
    0 => TagLib_ID3v2_Latin1,
    1 => TagLib_ID3v2_UTF16,
    2 => TagLib_ID3v2_UTF16BE,
    3 => TagLib_ID3v2_UTF8,
    _ => throw ArgumentError('Unknown value for TagLib_ID3v2_Encoding: $value'),
  };
}

final class TagLib_IOStream extends ffi.Struct {
  @ffi.Int()
  external int dummy;

  static ffi.Pointer<TagLib_IOStream> $allocate(
    ffi.Allocator $allocator, {
    required int dummy,
  }) => $allocator<TagLib_IOStream>()..ref.dummy = dummy;
}

final class TagLib_Tag extends ffi.Struct {
  @ffi.Int()
  external int dummy;

  static ffi.Pointer<TagLib_Tag> $allocate(
    ffi.Allocator $allocator, {
    required int dummy,
  }) => $allocator<TagLib_Tag>()..ref.dummy = dummy;
}

/// !
/// Discriminated union used in complex property attributes.
///
/// \e type must be set according to the \e value union used.
/// \e size is only required for TagLib_Variant_ByteVector and must contain
/// the number of bytes.
///
/// \related TagLib::Variant.
final class TagLib_Variant extends ffi.Struct {
  @ffi.UnsignedInt()
  external int typeAsInt;

  TagLib_Variant_Type get type => TagLib_Variant_Type.fromValue(typeAsInt);
  set type(TagLib_Variant_Type value) => typeAsInt = value.value;

  @ffi.UnsignedInt()
  external int size;

  external UnnamedUnion value;
}

/// !
/// Types which can be stored in a TagLib_Variant.
///
/// \related TagLib::Variant::Type
/// These correspond to TagLib::Variant::Type, but ByteVectorList, VariantList,
/// VariantMap are not supported and will be returned as their string
/// representation.
enum TagLib_Variant_Type {
  TagLib_Variant_Void(0),
  TagLib_Variant_Bool(1),
  TagLib_Variant_Int(2),
  TagLib_Variant_UInt(3),
  TagLib_Variant_LongLong(4),
  TagLib_Variant_ULongLong(5),
  TagLib_Variant_Double(6),
  TagLib_Variant_String(7),
  TagLib_Variant_StringList(8),
  TagLib_Variant_ByteVector(9);

  final int value;
  const TagLib_Variant_Type(this.value);

  static TagLib_Variant_Type fromValue(int value) => switch (value) {
    0 => TagLib_Variant_Void,
    1 => TagLib_Variant_Bool,
    2 => TagLib_Variant_Int,
    3 => TagLib_Variant_UInt,
    4 => TagLib_Variant_LongLong,
    5 => TagLib_Variant_ULongLong,
    6 => TagLib_Variant_Double,
    7 => TagLib_Variant_String,
    8 => TagLib_Variant_StringList,
    9 => TagLib_Variant_ByteVector,
    _ => throw ArgumentError('Unknown value for TagLib_Variant_Type: $value'),
  };
}

final class UnnamedUnion extends ffi.Union {
  external ffi.Pointer<ffi.Char> stringValue;

  external ffi.Pointer<ffi.Char> byteVectorValue;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> stringListValue;

  @ffi.Int()
  external int boolValue;

  @ffi.Int()
  external int intValue;

  @ffi.UnsignedInt()
  external int uIntValue;

  @ffi.LongLong()
  external int longLongValue;

  @ffi.UnsignedLongLong()
  external int uLongLongValue;

  @ffi.Double()
  external double doubleValue;
}
