name: Build macOS Native Library

on:
  push:
    tags:
    - 'v*'

  workflow_dispatch:


permissions:
  contents: write

jobs:
  build-macos:
    name: Build macOS Universal
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clone TagLib
      shell: bash
      run: |
        git clone \
          --depth 1 \
          --branch v2.3.1 \
          --recurse-submodules \
          https://github.com/taglib/taglib.git \
          taglib-src

    # ============================================================
    # Apple Silicon
    # ============================================================

    - name: Build arm64
      run: |
        cmake \
          -S taglib-src \
          -B build-arm64 \
          -DCMAKE_BUILD_TYPE=MinSizeRel \
          -DCMAKE_OSX_ARCHITECTURES=arm64 \
          -DBUILD_SHARED_LIBS=ON \
          -DBUILD_BINDINGS=ON \
          -DBUILD_TESTING=OFF \
          -DBUILD_EXAMPLES=OFF \
          -DCMAKE_C_FLAGS="-fPIC -Os -ffunction-sections -fdata-sections" \
          -DCMAKE_CXX_FLAGS="-fPIC -Os -ffunction-sections -fdata-sections"

        cmake --build build-arm64 --parallel

    # ============================================================
    # Intel macOS
    # ============================================================

    - name: Build x86_64
      run: |
        cmake \
          -S taglib-src \
          -B build-x86_64 \
          -DCMAKE_BUILD_TYPE=MinSizeRel \
          -DCMAKE_OSX_ARCHITECTURES=x86_64 \
          -DBUILD_SHARED_LIBS=ON \
          -DBUILD_BINDINGS=ON \
          -DBUILD_TESTING=OFF \
          -DBUILD_EXAMPLES=OFF \
          -DCMAKE_C_FLAGS="-fPIC -Os -ffunction-sections -fdata-sections" \
          -DCMAKE_CXX_FLAGS="-fPIC -Os -ffunction-sections -fdata-sections"

        cmake --build build-x86_64 --parallel

    # ============================================================
    # Create Universal Library
    # ============================================================

    - name: Create Universal Library
      run: |
        mkdir -p release/macos

        lipo \
          -create \
          build-arm64/taglib/libtag.dylib \
          build-x86_64/taglib/libtag.dylib \
          -output release/macos/libtag.dylib

        file release/macos/libtag.dylib

        lipo \
          -info \
          release/macos/libtag.dylib

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: taglib-macos
        path: release/
